doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'

        # only needed for MySQL
        charset: utf8mb4
        default_table_options:
            collate: utf8mb4_unicode_ci

        # backtrace queries in profiler (increases memory usage per request)
        #profiling_collect_backtrace: '%kernel.debug%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        second_level_cache:
            enabled: true
            region_cache_driver:
                type: pool
                pool: doctrine.second_level_cache_pool
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        dql:
            datetime_functions:
                TimestampDiff: App\DQL\TimestampDiff
                Day: App\DQL\Day
                Month: App\DQL\Month
                Date: App\DQL\Date
      #  metadata_cache_driver:
      #      type: service
      #      id: redis_cache_service
      #  result_cache_driver:
      #      type: service
      #      id: redis_cache_service
      #  query_cache_driver:
      #      type: service
      #      id: redis_cache_service

framework:
    cache:
        pools:
            doctrine.second_level_cache_pool:
                adapter: cache.app
