easy_admin:
  site_name: SokolStat
  entities:
          Tour:
            class: App\Entity\Tour
            list:
                fields:
                    - id
                    - country
                    - season
                    - data
                    - team
                    - team2
                    - goal1
                    - goal2
                    - bomb
                filters: ['team', 'team2', 'country', 'season']
          Eurocup:
            class: App\Entity\Eurocup
            list:
                fields:
                    - id
                    - turnir
                    - season
                    - data
                    - team
                    - team2
                    - score
                    - bomb
                    - number
                filters: ['team', 'team2', 'turnir', 'season', 'stadia', 'number']
          Rfplmatch:
            class: App\Entity\Rfplmatch
            list:
                fields:
                    - id
                    - tour
                    - season
                    - data
                    - team
                    - team2
                    - goal1
                    - goal2
                    - bomb
                    - player
                    - player2
                filters: ['team', 'team2', 'tour', 'season']
          Player:
            class: App\Entity\Player
            list:
                fields:
                    - id
                    - name
                    - translit
                    - born
                    - game
                    - goal
                    - sum
                    - lch_game
                    - lch_goal
                    - country
                filters: ['name', 'amplua', 'country']
          Shipplayer:
            class: App\Entity\Shipplayer
            list:
                fields:
                    - id
                    - player
                    - season
                    - team
                    - game
                    - goal
                    - cup
                    - supercup
                    - eurocup
                    - sum
                filters: ['season', 'team', 'player']
          News:
            class: App\Entity\News
            list:
                fields:
                    - id
                    - title
          Stadia:
            class: App\Entity\Stadia
            list:
              fields:
                - id
                - name
            form:
              fields:
                - name
                - alias
          Country:
            class: App\Entity\Country
            list:
                fields:
                    - id
                    - name
                filters: ['name']
          Team:
            class: App\Entity\Team
            list:
                fields:
                    - id
                    - name
                    - country
                filters: ['name', 'country']
            form:
                fields:
                  - name
                  - translit
                  - image
                  - image2
                  - country
                  - game
                  - wins
                  - nich
                  - porazh
                  - mz
                  - mp
                  - score
          Shiptable:
            class: App\Entity\Shiptable
            list:
                fields:
                    - id
                    - team
                    - wins
                    - nich
                    - porazh
                    - mz
                    - mp
                    - score
                filters: ['team', 'country', 'season']
          Ectable:
            class: App\Entity\Ectable
            list:
                fields:
                    - id
                    - team
                    - wins
                    - nich
                    - porazh
                    - mz
                    - mp
                    - score
                filters: ['team', 'turnir', 'season', 'stadia']
          Ecsostav:
            class: App\Entity\Ecsostav
            list:
                fields:
                    - id
                    - eurocup
                    - team
                    - team2
                filters: ['eurocup']
