easy_admin:
  site_name: SokolStat
  entities:
          Tour:
            class: App\Entity\Tour
            list:
                fields:
                    - id
                    - country
                    - season
                    - data
                    - team
                    - team2
                    - goal1
                    - goal2
                    - bomb
                filters: ['team', 'team2', 'country', 'season']
          Eurocup:
            class: App\Entity\Eurocup
            list:
                fields:
                    - id
                    - turnir
                    - season
                    - data
                    - team
                    - team2
                    - score
                    - bomb
                    - number
                filters: ['team', 'team2', 'turnir', 'season', 'stadia', 'number']
          Cup:
            class: App\Entity\Cup
            list:
                fields:
                    - id
                    - stadia
                    - season
                    - data
                    - team
                    - team2
                    - score
                    - bomb
                filters: ['team', 'team2', 'season', 'stadia']
          NationCup:
            class: App\Entity\NationCup
            list:
                fields:
                    - id
                    - stadia
                    - country
                    - season
                    - data
                    - team
                    - team2
                    - score
                    - bomb
                filters: ['team', 'team2', 'season', 'stadia', 'country']
          Rfplmatch:
            class: App\Entity\Rfplmatch
            list:
                fields:
                    - id
                    - tour
                    - season
                    - data
                    - team
                    - team2
                    - goal1
                    - goal2
                    - bomb
                    - player
                    - player2
                filters: ['team', 'team2', 'tour', 'season']
          Player:
            class: App\Entity\Player
            list:
                fields:
                    - id
                    - name
                    - translit
                    - born
                    - game
                    - goal
                    - sum
                    - lch_game
                    - lch_goal
                    - country
                filters: ['name', 'amplua', 'country']
            form:
                fields:
                    - name
                    - translit
                    - born
                    - country
                    - amplua
          Shipplayer:
            class: App\Entity\Shipplayer
            list:
                fields:
                    - id
                    - player
                    - season
                    - team
                    - game
                    - goal
                    - cup
                    - supercup
                    - eurocup
                    - sum
                filters: ['season', 'team', 'player']
            form:
                fields:
                    - player
                    - season
                    - team
                    - game
                    - goal
                    - cup
                    - supercup
                    - eurocup
                    - sum
          Cupplayer:
            class: App\Entity\Cupplayer
            list:
                fields:
                    - id
                    - player
                    - season
                    - team
                    - game
                    - goal
                filters: ['season', 'team', 'player']
            form:
                fields:
                    - player
                    - season
                    - team
                    - game
                    - goal
          Mundial:
            class: App\Entity\Mundial
            list:
                fields:
                    - id
                    - data
                    - turnir
                    - season
                    - country
                    - country2
                    - stadia
                    - score
                    - goal
                filters: ['season', 'turnir', 'country', 'country2']
            form:
                fields:
                    - data
                    - turnir
                    - season
                    - country
                    - country2
                    - stadia
                    - score
                    - goal
                    - city
                    - penalty
                    - game
                    - game2
                    - zriteli
                    - referee
                    - status
          Turnir:
            class: App\Entity\Turnir
            list:
                fields:
                    - id
                    - name
                    - alias
                    - russianalias
                filters: ['name', 'alias']
            form:
                fields:
                    - name
                    - alias
                    - russianalias
          Referee:
            class: App\Entity\Referee
            list:
                fields:
                    - id
                    - name
                    - country
                filters: ['name', 'country']
            form:
                fields:
                    - name
                    - country
          News:
            class: App\Entity\News
            list:
                fields:
                    - id
                    - title
          Newsdb:
            class: App\Entity\Newsdb
            list:
                fields:
                    - id
                    - news
                    - data
          Transfer:
            class: App\Entity\Transfer
            list:
                fields:
                    - id
                    - player
                    - old
                    - new
                filters: ['period', 'old', 'new', 'player']
          Period:
            class: App\Entity\Period
            list:
                fields:
                    - id
                    - name
                    - translit
            form:
              fields:
                - name
                - translit
          Stadia:
            class: App\Entity\Stadia
            list:
              fields:
                - id
                - name
            form:
              fields:
                - name
                - alias
          Country:
            class: App\Entity\Country
            list:
                fields:
                    - id
                    - name
                filters: ['name']
            form:
              fields:
                - name
                - translit
          Seasons:
            class: App\Entity\Seasons
            list:
                fields:
                    - id
                    - name
                filters: ['name']
            form:
              fields:
                - name
          City:
            class: App\Entity\City
            list:
                fields:
                    - id
                    - name
                filters: ['name']
            form:
              fields:
                - name
          Team:
            class: App\Entity\Team
            list:
                fields:
                    - id
                    - name
                    - country
                filters: ['name', 'country']
            form:
                fields:
                  - name
                  - translit
                  - image
                  - image2
                  - country
                  - game
                  - wins
                  - nich
                  - porazh
                  - mz
                  - mp
                  - score
          Shiptable:
            class: App\Entity\Shiptable
            list:
                fields:
                    - id
                    - team
                    - wins
                    - nich
                    - porazh
                    - mz
                    - mp
                    - score
                filters: ['team', 'country', 'season']
          Ectable:
            class: App\Entity\Ectable
            list:
                fields:
                    - id
                    - team
                    - wins
                    - nich
                    - porazh
                    - mz
                    - mp
                    - score
                filters: ['team', 'turnir', 'season', 'stadia']
            form:
                fields:
                    - turnir
                    - season
                    - stadia
                    - team
                    - wins
                    - nich
                    - porazh
                    - mz
                    - mp
                    - score
          MundialTable:
            class: App\Entity\MundialTable
            list:
                fields:
                    - id
                    - year
                    - stadia
                    - country
                    - wins
                    - nich
                    - porazh
                    - mz
                    - mp
                    - score
                filters: ['country', 'turnir', 'year', 'stadia']
            form:
                fields:
                    - turnir
                    - year
                    - stadia
                    - country
                    - wins
                    - nich
                    - porazh
                    - mz
                    - mp
                    - score
                    - seat
          Ecsostav:
            class: App\Entity\Ecsostav
            list:
                fields:
                    - id
                    - eurocup
                    - team
                    - team2
                filters: ['eurocup']
