twig:
    exception_controller: App\Controller\ExceptionController::showException
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        season: 2019-20
        stadia: groupA
        path_public: ''
