steam_fbstat_homepage:
    path:     /
    controller: App\Controller\NewsController::index

rating:
  path: /rating/
  controller: App\Controller\DefaultController::rating

nhl_add:
  path: /nhl/add/
  controller: App\Controller\NhlController::add
