steam_fbstat_homepage:
    path:     /
    controller: App\Controller\NewsController::index

soglasie:
    path:     /soglasie/
    controller: App\Controller\NewsController::soglasie

rating:
  path: /rating/
  controller: App\Controller\DefaultController::rating

nhl_add:
  path: /nhl/add/
  controller: App\Controller\NhlController::add

championships:
    path:  /championships/{country}/{season}/{tour}
    controller: App\Controller\ShiptableController:index
    defaults:
        tour: false
    requirements:
        country: russia|england|spain|italy|germany|france|fnl
        tour: \d+

championships_show:
    path:  /championships/{country}/{season}/{id}
    controller: App\Controller\ShiptableController:show
    requirements:
        country: russia|england|spain|italy|germany|france|fnl

championships_new:
    path:  /championships/admin/{id}
    controller: App\Controller\ShiptableController:new

championships_create:
    path:  /championships/admin/create/{id}
    controller: App\Controller\ShiptableController:create
    requirements: { _method: post }

championships_edit:
    path:  /championships/admin/edit/{id}/{country}
    controller: App\Controller\ShiptableController:edit
    requirements:
        id: \d+

championships_update:
    path:  /championships/admin/update/{id}/{country}
    controller: App\Controller\ShiptableController:update
    requirements: { _method: post }

championships_newSeason:
    path:  /championships/admin/season/{country}
    controller: App\Controller\ShiptableController:newSeason

championships_createSeason:
    path:  /championships/admin/season/create/{country}
    controller: App\Controller\ShiptableController:createSeason
    requirements: { _method: post }

championships_newMatch:
    path:  /championships/admin/{country}/{season}
    controller: App\Controller\ShiptableController:newMatch

championships_createMatch:
    path:  /championships/admin/create/{country}/{season}
    controller: App\Controller\ShiptableController:createMatch
    requirements: { _method: post }

championships_newrus:
    path:  /championships/admin/new/rus/{id}
    controller: App\Controller\ShiptableController:newRus

championships_createrus:
    path:  /championships/admin/create/match/rus/{id}
    controller: App\Controller\ShiptableController:createRus
    requirements: { _method: post }

cup:
    path:     /cup/{season}
    controller: App\Controller\CupController:index

cup_show:
    path:     /cup/{id}/{season}/show
    controller: App\Controller\CupController:show

cup_new:
    path:  /cup/admin/{id}
    controller: App\Controller\CupController:new
    requirements:
        id: \d+

cup_create:
    path:  /cup/admin/create/{id}
    controller: App\Controller\CupController:create
    requirements:
      _method: post
      id: \d+

cup_newMatch:
    path:  /cup/admin/{season}
    controller: App\Controller\CupController:newMatch

cup_createMatch:
    path:  /cup/admin/create/{season}
    controller: App\Controller\CupController:createMatch
    requirements: { _method: post }

nationcup:
    path:     /nationcup/{country}/{season}
    controller: App\Controller\NationcupController:index

nationcup_new:
    path:  /nationcup/admin/{id}/{country}
    controller: App\Controller\NationcupController:new
    requirements:
        id: \d+

nationcup_create:
    path:  /nationcup/admin/create/{id}/{country}
    controller: App\Controller\NationcupController:create
    requirements:
      _method: post
      id: \d+

nationcup_newMatch:
    path:  /nationcup/admin/{season}/{country}
    controller: App\Controller\NationcupController:newMatch

nationcup_createMatch:
    path:  /nationcup/admin/create/{season}/{country}
    controller: App\Controller\NationcupController:createMatch
    requirements: { _method: post }

eurocup:
    path:  /eurocup/{turnir}/{season}/{stadia}
    controller: App\Controller\EurocupController:index
    defaults:
      turnir: leagueChampions
      stadia: null
    requirements:
        turnir: leagueChampions|leagueEuropa|supercup|worldCupClub

eurocup_show:
    path:  /eurocup/{turnir}/{season}/{id}/show
    controller: App\Controller\EurocupController:show

eurocup_showTeam:
    path:  /eurocup/{season}/{turnir}/{id}/show/team
    controller: App\Controller\EurocupController:showTeam

eurocup_showmatch:
    path:  /eurocup/{turnir}/{season}/{id}/showmatch
    controller: App\Controller\EurocupController:showMatch
    requirements:
        id: \d+
        turnir: leagueChampions|leagueEuropa|supercup|worldCupClub

eurocup_edit:
    path:  /eurocup/{turnir}/{id}/{stadia}/edit
    controller: App\Controller\EurocupController:edit
    requirements:
        id: \d+

eurocup_update:
    path:  /eurocup/{turnir}/{id}/{stadia}/update
    controller: App\Controller\EurocupController:update
    requirements: { _method: post|put }

eurocup_newMatch:
    path:  /eurocup/admin/{season}
    controller: App\Controller\EurocupController:newMatch

eurocup_createMatch:
    path:  /eurocup/admin/create/{season}
    controller: App\Controller\EurocupController:createMatch
    requirements: { _method: post }

eurocup_new:
    path:  /eurocup/admin/{turnir}/{season}/{stadia}
    controller: App\Controller\EurocupController:new
    defaults:
      stadia: null
    requirements:
        turnir: leagueChampions|leagueEuropa|supercup|worldCupClub

eurocup_create:
    path:  /eurocup/admin/create/{turnir}/{season}/{stadia}
    controller: App\Controller\EurocupController:create
    defaults:
      stadia: null
    requirements: { _method: post }

supercup:
    path:  /supercup/{country}
    controller: App\Controller\UefaSupercupController:index

supercup_show:
    path:  /supercup/{country}/{id}
    controller: App\Controller\UefaSupercupController:show

sbornie_newMatch:
    path:  /sbornie/admin/{season}/{turnir}
    controller: App\Controller\MundialController:newMatch

sbornie_createMatch:
    path:  /sbornie/admin/create/{season}/{turnir}
    controller: App\Controller\MundialController:createMatch
    requirements: { _method: post }

sbornie:
    path:  /sbornie/{turnir}/{year}
    controller: App\Controller\MundialController:index

sbornieRus:
    path:  /sbornie/{season}
    controller: App\Controller\MundialController:showRus

sbornie_show:
    path:  /sbornie/{turnir}/{year}/{id}
    controller: App\Controller\MundialController:show
    requirements:
        id: \d+

sbornieCountry:
    path:  /sbornie/{turnir}/{year}/{country}
    controller: App\Controller\MundialController:showCountry

player:
    path:  /player/russia/{page}/{sort}/{order}/{team}/{country}
    controller: App\Controller\RusplayerController:index
    defaults:
      page: 1
      sort: game
      order: desc
      team: all
      country: false
    requirements:
        page: \d+
    options:
        expose: true

news_search:
    path:  /search
    controller: App\Controller\NewsController:search
    options:
        expose: true

player_search:
    path: /player/search
    controller: App\Controller\RusplayerController:search

player_show:
    path:  /player/{id}
    controller: App\Controller\RusplayerController:show

player_newSb:
    path:  /playeradmin/admin/sb/{season}
    controller: App\Controller\PlayerController:newSb

player_createSb:
    path:  /playeradmin/admin/createSb/{season}
    controller: App\Controller\PlayerController:createSb
    requirements: { _method: post }

player_newChamp:
    path:  /playeradmin/admin/champ/{season}/{team}
    controller: App\Controller\PlayerController:newChamp

player_createChamp:
    path:  /playeradmin/admin/createChamp/{season}/{team}
    controller: App\Controller\PlayerController:createChamp
    requirements: { _method: post }

player_newFnl:
    path:  /playeradmin/admin/fnl/{season}/{team}
    controller: App\Controller\PlayerController:newFnl

player_createFnl:
    path:  /playeradmin/admin/createFnl/{season}/{team}
    controller: App\Controller\PlayerController:createFnl
    requirements: { _method: post }

player_newPlayer:
    path:  /playeradmin/admin/newPlayer/{country}/{season}/{team}
    controller: App\Controller\PlayerController:newPlayer

player_createPlayer:
    path:  /admin/createNewPlayer/{country}/{season}/{team}
    controller: App\Controller\PlayerController:createNewPlayer
    requirements: { _method: post }

player_newChampNation:
    path:  /playeradmin/admin/champnation/{season}/{country}/{team}
    controller: App\Controller\PlayerController:newChampNation

player_createChampNation:
    path:  /playeradmin/admin/createChampnation/{season}/{country}/{team}
    controller: App\Controller\PlayerController:createChampNation
    requirements: { _method: post }

player_newlchplayer:
    path:  /playeradmin/admin/champnation/{season}/{team}
    controller: App\Controller\PlayerController:newLchPlayer

player_createlchplayer:
    path:  /playeradmin/admin/createChampnation/{season}/{team}
    controller: App\Controller\PlayerController:createLchPlayer
    requirements: { _method: post }

player_newRusplayer:
    path:  /playeradmin/admin/rusplayer/{season}/{team}/{country}
    controller: App\Controller\PlayerController:newRusplayer

player_createRusplayer:
    path:  /admin/createRusplayer/{season}/{team}/{country}
    controller: App\Controller\PlayerController:createRusplayer
    requirements: { _method: post }

player_newPlayersteam:
    path:  /playeradmin/admin/playersteam/{season}/{team}
    controller: App\Controller\PlayerController:newPlayersteam

player_createPlayersteam:
    path:  /playeradmin/admin/createPlayersteam/{season}/{team}
    controller: App\Controller\PlayerController:createPlayersteam
    requirements: { _method: post }

player_newEc:
    path:  /playeradmin/admin/ec/{turnir}/{season}/{team}
    controller: App\Controller\PlayerController:newEc

player_createEc:
    path:  /playeradmin/admin/createEc/{turnir}/{season}/{team}
    controller: App\Controller\PlayerController:createEc
    requirements: { _method: post }

player_newCup:
    path:  /playeradmin/admin/cup/{season}/{team}
    controller: App\Controller\PlayerController:newCup

player_createCup:
    path:  /playeradmin/admin/createCup/{season}/{team}
    controller: App\Controller\PlayerController:createCup
    requirements: { _method: post }

player_newSc:
    path:  /playeradmin/admin/sc/{season}/{team}/{id}
    controller: App\Controller\PlayerController:newSc

player_createSc:
    path:  /playeradmin/admin/createSc/{season}/{team}/{id}
    controller: App\Controller\PlayerController:createSc
    requirements: { _method: post }

player_editSb:
    path:  /playeradmin/admin/{id}/editSb/{season}/{change}
    controller: App\Controller\PlayerController:editSb

playeradmin_editChamp:
    path:  /playeradmin/admin/{id}/edit/{season}/{team}/{change}
    controller: App\Controller\PlayerController:editChamp

playeradmin_editFnl:
    path:  /playeradmin/admin/{id}/editFnl/{season}/{team}/{change}
    controller: App\Controller\PlayerController:editFnl

playeradmin_editTotalChamp:
    path:  /playeradmin/admin/totalChamp/{id}/edit/{season}/{team}/{change}
    controller: App\Controller\PlayerController:editTotalChamp

playeradmin_editTotal:
    path:  /playeradmin/admin/total/{id}/edit/{season}/{team}/{change}
    controller: App\Controller\PlayerController:editTotal

playeradmin_editTotalTeam:
    path:  /playeradmin/admin/totalTeam/{id}/edit/{season}/{team}/{change}
    controller: App\Controller\PlayerController:editTotalTeam

playeradmin_editCup:
    path:  /playeradmin/admin/cup/{id}/edit/{season}/{team}/{change}
    controller: App\Controller\PlayerController:editCup

playeradmin_editPlayerTurnirs:
    path:  /playeradmin/admin/editTurnirs/{season}/{country}/{team}
    controller: App\Controller\PlayerController:editPlayerTurnirs

playeradmin_updatePlayerTurnirs:
    path:  /playeradmin/admin/updateTurnirs/{season}/{country}/{team}
    controller: App\Controller\PlayerController:updatePlayerTurnirs
    requirements: { _method: post|put }

playeradmin_editNation:
    path:  /playeradmin/admin/{id}/editNation/{country}/{season}/{team}/{change}
    controller: App\Controller\PlayerController:editNation
    requirements:
        change: minus|plus

playeradmin_editLchplayer:
    path:  /playeradmin/admin/{id}/editLchplayer/{season}/{team}/{change}
    controller: App\Controller\PlayerController:editLchplayer

playeradmin_editEc:
    path:  /playeradmin/admin/{id}/editEc/{season}/{team}/{turnir}/{change}
    controller: App\Controller\PlayerController:editEc

admin_area:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
