steam_fbstat_homepage:
    path:     /
    controller: App\Controller\NewsController::index

soglasie:
    path:     /soglasie/
    controller: App\Controller\NewsController::soglasie

rating:
  path: /rating/
  controller: App\Controller\DefaultController::rating

nhl_add:
  path: /nhl/add/
  controller: App\Controller\NhlController::add

championships:
    path:  /championships/{country}/{season}/{tour}
    controller: App\Controller\ShiptableController:index
    defaults:
        tour: false
    requirements:
        country: russia|england|spain|italy|germany|france|fnl
        tour: \d+

championships_show:
    path:  /championships/{country}/{season}/{id}
    controller: App\Controller\ShiptableController:show
    requirements:
        country: russia|england|spain|italy|germany|france|fnl

championships_newMatch:
    path:  /championships/admin/{country}/{season}
    controller: App\Controller\ShiptableController:newMatch

championships_createMatch:
    path:  /championships/admin/create/{country}/{season}
    controller: App\Controller\ShiptableController:createMatch
    requirements: { _method: post }

championships_newrus:
    path:  /championships/admin/new/rus/{id}
    controller: App\Controller\ShiptableController:newRus

championships_createrus:
    path:  /championships/admin/create/match/rus/{id}
    controller: App\Controller\ShiptableController:createRus
    requirements: { _method: post }

championships_new:
    path:  /championships/admin/{id}
    controller: App\Controller\ShiptableController:new

championships_create:
    path:  /championships/admin/create/{id}
    controller: App\Controller\ShiptableController:create
    requirements: { _method: post }

cup:
    path:     /cup/{season}
    controller: App\Controller\CupController:index

cup_show:
    path:     /cup/{id}/{season}/show
    controller: App\Controller\CupController:show

nationcup:
    path:     /nationcup/{country}/{season}
    controller: App\Controller\NationcupController:index

eurocup:
    path:  /eurocup/{turnir}/{season}/{stadia}
    controller: App\Controller\EurocupController:index
    defaults:
      turnir: leagueChampions
      stadia: null
    requirements:
        turnir: leagueChampions|leagueEuropa|supercup|worldCupClub

eurocup_show:
    path:  /eurocup/{turnir}/{season}/{id}/show
    controller: App\Controller\EurocupController:show

eurocup_showTeam:
    path:  /eurocup/{season}/{turnir}/{id}/show/team
    controller: App\Controller\EurocupController:showTeam

eurocup_showmatch:
    path:  /eurocup/{turnir}/{season}/{id}/showmatch
    controller: App\Controller\EurocupController:showMatch
    requirements:
        id: \d+
        turnir: leagueChampions|leagueEuropa|supercup|worldCupClub

eurocup_edit:
    path:  /eurocup/{turnir}/{id}/edit
    controller: App\Controller\EurocupController:edit
    requirements:
        id: \d+

supercup:
    path:  /supercup/{country}
    controller: App\Controller\UefaSupercupController:index

supercup_show:
    path:  /supercup/{country}/{id}
    controller: App\Controller\UefaSupercupController:show

sbornie:
    path:  /sbornie/{turnir}/{year}
    controller: App\Controller\MundialController:index

sbornieRus:
    path:  /sbornie/{season}
    controller: App\Controller\MundialController:showRus

sbornie_show:
    path:  /sbornie/{turnir}/{year}/{id}
    controller: App\Controller\MundialController:show
    requirements:
        id: \d+

sbornieCountry:
    path:  /sbornie/{turnir}/{year}/{country}
    controller: App\Controller\MundialController:showCountry

player:
    path:  /player/russia/{page}/{sort}
    controller: App\Controller\RusplayerController:index
    defaults:
      page: 1
      sort: game
    requirements:
        page: \d+

player_show:
    path:  /player/{id}
    controller: App\Controller\RusplayerController:show

admin_area:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
